name: RDP Workflow

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Install OpenSSH Client
      run: Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0

    - name: Create TCP Tunnel using Serveo
      run: |
        Start-Process -NoNewWindow -FilePath 'C:\Windows\System32\OpenSSH\ssh.exe' -ArgumentList '-R 3389:localhost:3389 serveo.net' -Wait
      shell: pwsh

    - name: Output Serveo Tunnel Info
      run: |
        ssh -R 3389:localhost:3389 serveo.net
      shell: pwsh
