name: RDP Workflow with tmate

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Install tmate for Windows
      run: |
        curl -L https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-msysgit-msys2-x86_64.tar.xz -o tmate.tar.xz
        tar -xf tmate.tar.xz
        Move-Item -Path tmate-2.4.0-static-msysgit-msys2-x86_64/tmate.exe -Destination C:/Windows/System32/tmate.exe

    - name: Start tmate session
      run: |
        tmate -S /tmp/tmate.sock new-session -d
      shell: pwsh

    - name: Display tmate SSH connection info
      run: |
        tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
      shell: pwsh
